// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgzsxcqskuiosvejvnxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnenN4Y3Fza3Vpb3N2ZWp2bnhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNDMzOTQsImV4cCI6MjA1NTgxOTM5NH0.RypJsk9s52RWHCpmtLfvd8sWO8I_HrKt4fqEjgF1VLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);